[package]
name = "groovy2kts"
version = "0.1.0"
authors = ["ranaaditya <mail2aditya.rana98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
